# Generated by Django 4.1.13 on 2024-08-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_image_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='ID',
            new_name='id',
        ),
    ]
