# Generated by Django 4.1.13 on 2024-08-23 07:37

from django.db import migrations, models
import enums.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('name_customer', models.CharField(max_length=255)),
                ('id_customer', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('payment_method', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('check_in_datetime', models.DateTimeField(blank=True, null=True)),
                ('check_out_datetime', models.DateTimeField(blank=True, null=True)),
                ('service_use', models.JSONField()),
                ('status', models.CharField(blank=True, default=enums.enums.StatusOrder['PENDING'], max_length=255)),
            ],
        ),
    ]
