# Generated by Django 4.1.13 on 2024-08-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
